export const CourseStatus = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
}

export const CourseCategory = {
  DEVELOPMENT: 'DEVELOPMENT',
  BUSINESS: 'BUSINESS',
  DESIGN: 'DESIGN',
  MARKETING: 'MARKETING',
  IT: 'IT',
  PERSONAL_DEVELOPMENT: 'PERSONAL_DEVELOPMENT',
  PHOTOGRAPHY: 'PHOTOGRAPHY',
  MUSIC: 'MUSIC',
  HEALTH: 'HEALTH',
  FITNESS: 'FITNESS',
  LIFESTYLE: 'LIFESTYLE',
  TEACHING: 'TEACHING',
  ACADEMICS: 'ACADEMICS',
  LANGUAGE: 'LANGUAGE',
  OTHER: 'OTHER',
}
