const QUERY_KEYS = {
  REFRESH_TOKEN: 'REFRESH_TOKEN',

  GET_LIST_COURSES_MANAGER: 'GET_LIST_COURSES_MANAGER',
  GET_LIST_COURSES_PUBLIC: 'GET_LIST_COURSES_PUBLIC',
  GET_DETAIL_COURSE: 'GET_DETAIL_COURSE',
  GET_DETAIL_COURSE_PUBLIC: 'GET_DETAIL_COURSE_PUBLIC',
  CREATE_COURSE_DRAFT: '',
  CREATE_PART_COURSE: '',
  EDIT_COURSE: '',
  EDIT_PART_COURSE: '',
  // CREATE_PART_COURSE: '',
  // CREATE_PART_COURSE: '',
  // CREATE_PART_COURSE: '',
  // CREATE_PART_COURSE: '',
  GET_COURSE_OWNER: 'GET_COURSE_OWNER',

  CREATE_LESSON: '',
  GET_LIST_LESSONS_MANAGER: 'GET_LIST_LESSONS_MANAGER',
  GET_LESSONS_PUBLIC: 'GET_LESSONS_PUBLIC',
  EDIT_LESSON: '',
  APPROVE_LESSON: 'APPROVE_LESSON',

  // interact keys
  GET_INTERACTS: 'GET_INTERACTS',
  COMMENT: 'COMMENT',
  VOTE_COMMENT: 'VOTE_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  UPDATE_COMMENT: 'UPDATE_COMMENT',
  HEART: 'HEART',
}

export default QUERY_KEYS
