const QUERY_KEYS = {
  REFRESH_TOKEN: 'REFRESH_TOKEN',

  GET_LIST_COURSES_MANAGER: 'GET_LIST_COURSES_MANAGER',
  GET_LIST_COURSES_PUBLIC: 'GET_LIST_COURSES_PUBLIC',
  GET_DETAIL_COURSE: 'GET_DETAIL_COURSE',
  GET_DETAIL_COURSE_PUBLIC: 'GET_DETAIL_COURSE_PUBLIC',
  CREATE_COURSE_DRAFT: '',
  CREATE_PART_COURSE: '',
  EDIT_COURSE: '',
  EDIT_PART_COURSE: '',
  // CREATE_PART_COURSE: '',
  // CREATE_PART_COURSE: '',
  // CREATE_PART_COURSE: '',
  // CREATE_PART_COURSE: '',
  GET_COURSE_OWNER: 'GET_COURSE_OWNER',

  CREATE_LESSON: '',
  GET_LIST_LESSONS_MANAGER: 'GET_LIST_LESSONS_MANAGER',
  GET_LESSONS_PUBLIC: 'GET_LESSONS_PUBLIC',
  EDIT_LESSON: '',
  APPROVE_LESSON: 'APPROVE_LESSON',

  // interact keys
  GET_INTERACTS: 'GET_INTERACTS',
  GET_LIST_RATES: 'GET_LIST_RATES',
  COMMENT: 'COMMENT',
  VOTE_COMMENT: 'VOTE_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  UPDATE_COMMENT: 'UPDATE_COMMENT',
  HEART: 'HEART',

  // campaign keys
  GET_CAMPAIGN: 'GET_CAMPAIGN',
  CREATE_CAMPAIGN: 'CREATE_CAMPAIGN',
  UPDATE_CAMPAIGN: 'UPDATE_CAMPAIGN',
  GET_LIST_CAMPAIGNS: 'GET_LIST_CAMPAIGNS',
  GET_LIST_CAMPAIGNS_PUBLIC: 'GET_LIST_CAMPAIGNS_PUBLIC',
  GET_DETAIL_CAMPAIGN: 'GET_DETAIL_CAMPAIGN',
  GET_DETAIL_CAMPAIGN_PUBLIC: 'GET_DETAIL_CAMPAIGN_PUBLIC',
  GET_MY_PROMOTIONS: 'GET_MY_PROMOTIONS',

  // cart
  GET_MY_CART: 'GET_MY_CART',
  ADD_TO_CART: 'ADD_TO_CART',

  // report
  GET_REPORT_SYSTEM: 'GET_REPORT_SYSTEM',
  GET_REPORT_AUTHOR: 'GET_REPORT_AUTHOR',
  GET_REPORT_COURSE: 'GET_REPORT_COURSE',

  // conversation
  GET_LIST_CONVERSATIONS: 'GET_LIST_CONVERSATIONS',
  CREATE_CONVERSATION: 'CREATE_CONVERSATION',
  GET_CONVERSATION_PUBLIC: 'GET_CONVERSATION_PUBLIC',

  // user
  GET_USER: 'GET_USER',
  GET_LIST_USERS: 'GET_LIST_USERS',
  SEARCH_USER: 'SEARCH_USER',
  SEARCH_AUTHOR: 'SEARCH_AUTHOR',

  // up role
  GET_LIST_UP_ROLE: 'GET_LIST_UP_ROLE',
  GET_MY_UP_ROLE_REQUEST: 'GET_MY_UP_ROLE_REQUEST',
  GET_DETAIL_UP_ROLE_REQUEST: 'GET_DETAIL_UP_ROLE_REQUEST',
}

export default QUERY_KEYS
