import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import RootProvider from '@/contexts/root'
import 'react-toastify/dist/ReactToastify.css'
import 'react-date-picker/dist/DatePicker.css'
import 'react-calendar/dist/Calendar.css'
import 'swiper/css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'KGB Hub',
  description:
    'Skills for your present (and your future). Get started with us.Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning={false}>
      <body className={`${inter.className} bg-background`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  )
}
